package jospehsportal;

import com.gargoylesoftware.htmlunit.html.HtmlAnchor;
import com.gargoylesoftware.htmlunit.html.HtmlPage;
import java.awt.Color;
import java.awt.Font;
import java.io.IOException;
import java.util.Arrays;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author RK
 */
public class Marks extends javax.swing.JFrame {    /**
     * Creates new form Menu
     */
    //static Portal p=null;
    Portal p=new Portal("19IT152","3md4ue548");
    HtmlPage studview=p.login();
    //static HtmlPage studview=null;
    public Marks(){
        initComponents();               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Back = new javax.swing.JLabel();
        title1 = new javax.swing.JLabel();
        marks = new javax.swing.JLabel();
        welcome = new javax.swing.JLabel();
        bluebg = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        error = new javax.swing.JLabel();
        scrollpane = new javax.swing.JScrollPane();
        markstable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(650, 440));

        Back.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Back.setForeground(new java.awt.Color(255, 255, 255));
        Back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Back.setText("Back");
        Back.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });

        title1.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        title1.setForeground(new java.awt.Color(255, 255, 255));
        title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title1.setText("St. Joseph's College Of Engineering");

        marks.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        marks.setForeground(new java.awt.Color(255, 255, 255));
        marks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        marks.setText("Marks View");

        welcome.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        welcome.setText("Welcome,");

        bluebg.setBackground(new java.awt.Color(45, 182, 224));
        bluebg.setOpaque(true);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "1", "2", "3", "4", "5", "6", "7", "8" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Semester :");

        jLabel2.setText("Test Type:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "IAE-1 Unit 1", "IAE-2 Unit 2", "IAE-3 Unit 3", "IAE-4 Unit 4", "Model 1", "Model 2", "Model 3", "Cycle Test 1", "Cycle Test 2", "Cycle Test 3" }));

        error.setForeground(new java.awt.Color(255, 0, 0));
        error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        scrollpane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        markstable.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        markstable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {" No", "Data", "Available"}
            },
            new String [] {
                "Subject Code", "Marks", "Remark"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        markstable.setEnabled(false);
        markstable.setRowHeight(20);
        markstable.setRowSelectionAllowed(false);
        markstable.setShowVerticalLines(false);
        markstable.getTableHeader().setResizingAllowed(false);
        markstable.getTableHeader().setReorderingAllowed(false);
        scrollpane.setViewportView(markstable);

        jButton1.setText("Fetch");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(bluebg, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(marks, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(jButton1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(error, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(scrollpane, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bluebg, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(Back))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(marks, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(error, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(scrollpane, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 610));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        new Menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackMouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed
    
    JLabel[] sub=null;
    JLabel title=new JLabel();
    int len=0;
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String sem=jComboBox1.getSelectedItem().toString();
        String test=jComboBox2.getSelectedItem().toString();

        if(len != 0 ){
            title.setText("");
            title.setVisible(false);

            for(JLabel l: sub){
             //  l.setText(""); 
               l.setVisible(false);
            }
             len=0;
        }
        
        DefaultTableModel m=(DefaultTableModel) markstable.getModel();
        m.setRowCount(0);
        scrollpane.setSize(scrollpane.getWidth(), 47);
        markstable.setSize(scrollpane.getWidth(), 20);
        if(sem.equals("Choose") || test.equals("Choose")){                
                m.setRowCount(0);
                scrollpane.setSize(scrollpane.getWidth(), 47);
                markstable.setSize(scrollpane.getWidth(), 20);
                String[] a={"Enter","Valid","Option"};
                m.addRow(a);
                
        }
        else{    
            
            String[][] data=p.DisplayMarks(sem, test, studview);
            
            if(data.length==0){   
                
                //DefaultTableModel m=(DefaultTableModel) markstable.getModel();
                m.setRowCount(0);
                scrollpane.setSize(scrollpane.getWidth(), 47);
                markstable.setSize(scrollpane.getWidth(), 20);
                String[] a={" No","Data","Available"};
                m.addRow(a);  
                
            }
            else{  
               
                //DefaultTableModel m= (DefaultTableModel) markstable.getModel();
                m.setRowCount(0);
                scrollpane.setSize(scrollpane.getWidth(),27+(20*data.length));
                markstable.setSize(scrollpane.getWidth(),(20*data.length));
               
                for(int row=0;row<data.length;row++){                
                    String code=data[row][1];
                    String mark=data[row][2];
                    String remark=data[row][3];
                    String[] a={code,mark,remark};
                    m.addRow(a);
                }
                
                int x_cord=50;                
                int y_cord=220+markstable.getHeight();
                //System.out.println(markstable.getHeight());
               // title=new JLabel();
               if(title==null){
                    title=new JLabel();
                    jPanel1.add(title);

               }
                title.setSize(500,30);
                title.setText("   Subject Code  :       Subject Name");
                title.setFont(new Font("Calibri", Font.BOLD, 18));
                
                title.setLocation(x_cord, y_cord);
                
                y_cord+=30;
                x_cord+=20;
                
                sub=new JLabel[data.length];
                int max_len=0;
                for(int i=0;i<sub.length;i++){
                    len+=1;
                    
                    if(y_cord>jPanel1.getHeight()){
                        y_cord=markstable.getY()+(55*data.length+1)+35;
                        x_cord+=max_len+10;
                    }
                    
                    sub[i]=new JLabel(); 
                    sub[i].setSize(500,30);
                    sub[i].setFont(new Font("Calibri", Font.BOLD, 16));
                    String x=data[i][1]+" : "+data[i][0];
                    if(x.length()>max_len){
                        max_len=x.length();
                    }
                    sub[i].setText("* "+data[i][1]+" :     "+data[i][0]);      
                    jPanel1.add(sub[i]);
                    sub[i].setLocation(x_cord, y_cord);
                    y_cord+=20;                   
                }              
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Marks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Back;
    private javax.swing.JLabel bluebg;
    private javax.swing.JLabel error;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JLabel marks;
    private javax.swing.JTable markstable;
    private javax.swing.JScrollPane scrollpane;
    private javax.swing.JLabel title1;
    public javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
