package jospehsportal;

import com.gargoylesoftware.htmlunit.html.HtmlPage;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author RK
 */
public class Notes extends javax.swing.JFrame {

    /**
     * Creates new form Notes
     */
    static Portal p=null;
    static HtmlPage studp=null;
    public Notes() {
        initComponents();
        String[] years=p.FetchNoteYears(studp);
        year.setModel(new javax.swing.DefaultComboBoxModel<>(years));        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Back = new javax.swing.JLabel();
        stjoseph = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        yearlabel = new javax.swing.JLabel();
        year = new javax.swing.JComboBox<>();
        Course = new javax.swing.JLabel();
        Semesterlabel = new javax.swing.JLabel();
        semester = new javax.swing.JComboBox<>();
        subjectabel = new javax.swing.JLabel();
        subject = new javax.swing.JComboBox<>();
        subjectabel1 = new javax.swing.JLabel();
        notes = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Back.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Back.setForeground(new java.awt.Color(255, 255, 255));
        Back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Back.setText("Back");
        Back.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });
        jPanel1.add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, -1));

        stjoseph.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        stjoseph.setForeground(new java.awt.Color(255, 255, 255));
        stjoseph.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stjoseph.setText("St. Joseph's College Of Engineering");
        jPanel1.add(stjoseph, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 40));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Notes Download");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 730, 40));

        jLabel1.setBackground(new java.awt.Color(0, 90, 140));
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 77));

        yearlabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        yearlabel.setText("Academic Year");
        jPanel1.add(yearlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 120, 30));

        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", " " }));
        jPanel1.add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 100, 30));

        Course.setText("Course");
        jPanel1.add(Course, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 86, 240, 20));

        Semesterlabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Semesterlabel.setText("Semester");
        jPanel1.add(Semesterlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 120, 30));

        semester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "1", "2", "3", "4", "5", "6", "7", "8" }));
        jPanel1.add(semester, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 100, 30));

        subjectabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        subjectabel.setText("Subject Name");
        jPanel1.add(subjectabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 120, 30));

        subject.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", " " }));
        jPanel1.add(subject, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 100, 30));

        subjectabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        subjectabel1.setText("Notes Type");
        jPanel1.add(subjectabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 120, 30));

        notes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", " " }));
        notes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notesActionPerformed(evt);
            }
        });
        jPanel1.add(notes, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 100, 30));

        jButton1.setText("Go");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, -1, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        new Menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackMouseClicked

    private void notesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Notes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Notes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Notes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Notes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Notes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Back;
    private javax.swing.JLabel Course;
    private javax.swing.JLabel Semesterlabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private static javax.swing.JComboBox<String> notes;
    private javax.swing.JComboBox<String> semester;
    private javax.swing.JLabel stjoseph;
    private static javax.swing.JComboBox<String> subject;
    private javax.swing.JLabel subjectabel;
    private javax.swing.JLabel subjectabel1;
    private static javax.swing.JComboBox<String> year;
    private javax.swing.JLabel yearlabel;
    // End of variables declaration//GEN-END:variables
}
